name: env
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=5_kmp_llvm
  - _python_abi3_support=1.0=hd8ed1ab_2
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.2=py310h5541b7b_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - async-timeout=5.0.1=pyhd8ed1ab_1
  - attrs=25.4.0=pyh71513ae_0
  - aws-c-auth=0.9.1=h194c533_5
  - aws-c-cal=0.9.8=h346e085_0
  - aws-c-common=0.12.5=hb03c661_0
  - aws-c-compression=0.3.1=h7e655bb_7
  - aws-c-event-stream=0.5.6=h1deb5b9_4
  - aws-c-http=0.10.7=had4b759_1
  - aws-c-io=0.23.2=hbff472d_2
  - aws-c-mqtt=0.13.3=h8ba2272_8
  - aws-c-s3=0.8.6=h493c25d_7
  - aws-c-sdkutils=0.2.4=h7e655bb_2
  - aws-checksums=0.2.7=h7e655bb_3
  - aws-crt-cpp=0.35.0=h719b17a_2
  - aws-sdk-cpp=1.11.606=h522d481_6
  - azure-core-cpp=1.16.1=h3a458e0_0
  - azure-identity-cpp=1.13.2=h3a5f585_1
  - azure-storage-blobs-cpp=12.15.0=h2a74896_1
  - azure-storage-common-cpp=12.11.0=h3d7a050_1
  - azure-storage-files-datalake-cpp=12.13.0=hf38f1be_1
  - brotli-python=1.2.0=py310h8cfb67f_0
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=2.0.0=py310he7384ee_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - cpython=3.10.19=py310hd8ed1ab_2
  - datasets=2.14.4=pyhd8ed1ab_0
  - dill=0.3.7=pyhd8ed1ab_0
  - filelock=3.20.0=pyhd8ed1ab_0
  - frozenlist=1.7.0=py310h9548a50_0
  - fsspec=2025.10.0=pyhd8ed1ab_0
  - gflags=2.2.2=h5888daf_1005
  - glog=0.7.1=hbabe93e_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py310h63ebcad_1
  - h2=4.3.0=pyhcf101f3_0
  - hf-xet=1.2.0=py310hb823017_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - huggingface_hub=0.36.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.44=h1aa0949_4
  - libabseil=20250512.1=cxx17_hba17884_0
  - libarrow=22.0.0=h99e40f8_3_cpu
  - libarrow-acero=22.0.0=h635bf11_3_cpu
  - libarrow-compute=22.0.0=h8c2c5c3_3_cpu
  - libarrow-dataset=22.0.0=h635bf11_3_cpu
  - libarrow-substrait=22.0.0=h3f74fd7_3_cpu
  - libblas=3.9.0=38_h5875eb1_mkl
  - libbrotlicommon=1.2.0=h09219d5_0
  - libbrotlidec=1.2.0=hd53d788_0
  - libbrotlienc=1.2.0=h02bd7ab_0
  - libcblas=3.9.0=38_hfef963f_mkl
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcurl=8.17.0=h4e3cde8_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.1=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgomp=15.2.0=h767d61c_7
  - libgoogle-cloud=2.39.0=hdb79228_0
  - libgoogle-cloud-storage=2.39.0=hdbdcf42_0
  - libgrpc=1.73.1=h3288cfb_1
  - libhwloc=2.12.1=default_h7f8ec31_1002
  - libiconv=1.18=h3b78370_2
  - liblapack=3.9.0=38_h5e43f62_mkl
  - liblzma=5.8.1=hb9d3cd8_2
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libopentelemetry-cpp=1.21.0=hb9b0907_1
  - libopentelemetry-cpp-headers=1.21.0=ha770c72_1
  - libparquet=22.0.0=h7376487_3_cpu
  - libprotobuf=6.31.1=h49aed37_2
  - libre2-11=2025.11.05=h7b12aa8_0
  - libsentencepiece=0.2.1=h022d5ca_0
  - libsqlite=3.51.0=hee844dc_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libthrift=0.22.0=h454ac66_1
  - libtorch=2.8.0=cpu_mkl_h09b866c_102
  - libutf8proc=2.11.0=hb04c3b8_0
  - libuuid=2.41.2=he9a06e4_0
  - libuv=1.51.0=hb03c661_1
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.15.1=h26afc86_0
  - libxml2-16=2.15.1=ha9997c6_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=21.1.5=h4922eb0_0
  - lz4-c=1.10.0=h5888daf_1
  - marisa-trie=1.2.1=py310hea6c23e_1
  - markupsafe=3.0.3=py310h3406613_0
  - mkl=2025.3.0=h0e700b2_462
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - multidict=6.6.3=py310h89163eb_0
  - multiprocess=0.70.15=py310h2372a71_1
  - ncurses=6.5=h2d0b736_3
  - networkx=3.4.2=pyh267e887_2
  - nlohmann_json=3.12.0=h54a6638_1
  - numpy=2.2.6=py310hefbff90_0
  - openssl=3.5.4=h26f9b46_0
  - optree=0.17.0=py310h03d9f68_2
  - orc=2.2.1=hd747db4_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py310h0158d43_1
  - pip=25.2=pyh8b19718_0
  - prometheus-cpp=1.3.0=ha5d0236_0
  - propcache=0.3.1=py310h89163eb_0
  - pyarrow=22.0.0=py310hff52083_0
  - pyarrow-core=22.0.0=py310h923f568_0_cpu
  - pybind11=2.13.6=pyhc790b64_3
  - pybind11-abi=4=hd8ed1ab_3
  - pybind11-global=2.13.6=pyh217bc35_3
  - pycparser=2.22=pyh29332c3_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.19=h3c07f61_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.10.19=hd8ed1ab_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python-xxhash=3.6.0=py310hf3bd8b6_1
  - python_abi=3.10=8_cp310
  - pytorch=2.8.0=cpu_mkl_py310_hf99aa82_102
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py310h3406613_0
  - re2=2025.11.05=h5301d42_0
  - readline=8.2=h8c095d6_2
  - regex=2025.11.3=py310h7c4b9e2_1
  - requests=2.32.5=pyhd8ed1ab_0
  - s2n=1.6.0=h8399546_1
  - safetensors=0.6.2=py310hdfeec95_1
  - sentencepiece=0.2.1=h7197b3e_0
  - sentencepiece-python=0.2.1=py310he011bb3_0
  - sentencepiece-spm=0.2.1=h022d5ca_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - sleef=3.9.0=ha0421bc_0
  - snappy=1.2.2=h03e3b7b_0
  - sympy=1.14.0=pyh2585a3b_105
  - tbb=2022.3.0=h8d10470_1
  - tk=8.6.13=noxft_hd72426e_102
  - tokenizers=0.22.1=py310h04b4747_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - transformers=4.57.1=pyhd8ed1ab_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xxhash=0.8.3=hb47aa4a_0
  - yaml=0.2.5=h280c20c_3
  - yarl=1.22.0=py310h3406613_0
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.25.0=py310h139afa4_1
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - aenum==3.1.15
      - aioboto3==15.5.0
      - aiobotocore==2.25.1
      - aiofiles==25.1.0
      - aioitertools==0.13.0
      - antlr4-python3-runtime==4.13.2
      - anyio==4.11.0
      - beautifulsoup4==4.14.2
      - boto3==1.40.61
      - botocore==1.40.61
      - chardet==5.2.0
      - colorlog==6.10.1
      - dataproperty==1.1.0
      - debugpy==1.8.17
      - distro==1.9.0
      - docstring-parser==0.17.0
      - exceptiongroup==1.3.0
      - frozendict==2.4.6
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - ijson==3.4.0.post0
      - inspect-ai==0.3.144
      - jiter==0.11.1
      - jmespath==1.0.1
      - joblib==1.5.2
      - jsonlines==4.0.0
      - jsonpatch==1.33
      - jsonpath-ng==1.7.0
      - jsonpointer==3.0.0
      - jsonref==1.1.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - langcodes==3.5.0
      - language-data==1.3.0
      - latex2sympy2-extended==1.0.6
      - lighteval==0.12.1
      - linkify-it-py==2.0.3
      - lxml==6.0.2
      - markdown-it-py==4.0.0
      - mbstrdecoder==1.1.4
      - mdit-py-plugins==0.5.0
      - mdurl==0.1.2
      - mmh3==5.2.0
      - nest-asyncio==1.6.0
      - nltk==3.9.1
      - openai==2.7.1
      - pathlib-abc==0.5.2
      - pathvalidate==3.3.1
      - platformdirs==4.5.0
      - ply==3.11
      - portalocker==3.2.0
      - pycountry==24.6.1
      - pygments==2.19.2
      - pytablewriter==1.2.1
      - python-dotenv==1.2.1
      - referencing==0.37.0
      - rich==14.2.0
      - rouge-score==0.1.2
      - rpds-py==0.28.0
      - s3fs==2025.3.0
      - s3transfer==0.14.0
      - sacrebleu==2.5.1
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - semver==3.0.4
      - shellingham==1.5.4
      - shortuuid==1.0.13
      - sniffio==1.3.1
      - soupsieve==2.8
      - tabledata==1.3.4
      - tabulate==0.9.0
      - tcolorpy==0.1.7
      - tenacity==9.1.2
      - termcolor==2.3.0
      - textual==6.5.0
      - threadpoolctl==3.6.0
      - typepy==1.3.4
      - typer==0.20.0
      - uc-micro-py==1.0.3
      - universal-pathlib==0.3.4
      - wrapt==1.17.3
prefix: /home/lsfragar/.conda/envs/env
